# Details: https://prometheus.io/docs/alerting/latest/configuration/
alertmanagerFiles:
  alertmanager.yml:
    global: {}
    receivers:
      - name: default-receiver
      - name: rollback-webhook
        webhook_configs:
          - url: "http://rollback.bofa.svc/api/"
    route:
      # how long do I wait before I trigger an alert
      group_wait: 0s
      # how long do I wait before I trigger a new alert if a change occurs after an initial alert
      group_interval: 30s
      receiver: default-receiver
      repeat_interval: 10m
      
      routes: 
        - receiver: rollback-webhook
          match_re:
            severity: rollback
# Details: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
serverFiles:
  alerting_rules.yml:
    groups:
    - name: deployment state
      rules:
      - alert: PodUnscheduleable
        expr: sum by (pod) (kube_pod_status_unschedulable) > 0
        # how long do I wait (and keep scraping the api) before I go from pending to active alert
        for: 20s
        labels:
          severity: rollback
        annotations:
          summary: "Pod {{ $labels.pod }} update is unschedulable"
          description: "Pod {{ $labels.pod }} has be unschedulable for more than 3 minutes.  Rollback should trigger"
